app-name = "Metro"
time-multiplier = 10

pekko.actor.default-dispatcher {
  throughput = 10
  executor = "thread-pool-executor"
  thread-pool-executor {
    core-pool-size-min    = 4
    core-pool-size-factor = 1.0
    max-pool-size         = 32
  }
}