// Metro. SDMT

import scala.concurrent.duration.DurationInt
import scala.util.{Failure, Random, Success, Try}

import play.api.libs.json._

import org.apache.pekko.actor.typed.{ActorRef, ActorSystem, Behavior}
import org.apache.pekko.actor.typed.scaladsl.Behaviors
import org.apache.pekko.actor.typed.scaladsl.adapter._
import org.apache.pekko.http.scaladsl.Http
import org.apache.pekko.http.scaladsl.server.Directives.{handleWebSocketMessages, path}
import org.apache.pekko.http.scaladsl.server.Route

import parser.{DistrictData, Entrance, EntranceParser, MetroParser, ODMatrix, ODParser, Path, StationIds, StationParser}
import pureconfig._
import pureconfig.generic.auto._
import scalax.collection.Graph
import scalax.collection.edge.WDiEdge
import scribe.Level
import messages.Messages._
import utils.WebSocket


object Main {

  def main(args: Array[String]): Unit = {

    // Read configuration
    val metroConf = ConfigSource.default.load[MetroConf].toOption.get
    scribe.Logger.root
      .clearHandlers()
      .clearModifiers()
      .withHandler(minimumLevel = Some(Level.Info))
      .replace()
    val speedFactor: Double = metroConf.timeMultiplier.toDouble
    scribe.info(s"Metro starting. Sim speed: ${speedFactor}× real time")
    SimClock.setSpeed(speedFactor)
    SimClock.start()
    // Pre-populate snapshot so connecting clients know simulation starts paused
    WebSocket.sendStat("simPaused", """{"message": "simPaused", "paused": true}""")

    // Get daily entrance data
    val entrance: String = scala.io.Source.fromFile("data/entrance.json").mkString
    val entrances: Seq[Entrance] = new EntranceParser().parseEntrances(entrance)

    // Get station IDs
    val stationId: String = scala.io.Source.fromFile("data/stations.json").mkString
    val stationIds: Seq[StationIds] = new StationParser().parseStations(stationId)

    // Build station → entrance map
    val stationIdsEntrance: Map[StationIds, Option[Entrance]] = stationIds
      .map(s => s -> entrances.find(e => e.id == Integer.valueOf(s.secondaryId).toString))
      .toMap
      .filter { case (_, v) => v.isDefined }

    // Metro network
    val metro: String = scala.io.Source.fromFile("data/tramos.json").mkString
    val paths: Seq[Path] = new MetroParser(metro).parseMetro(metro)

    val sortedLinePaths: Map[String, Seq[Path]] = paths
      .groupBy(_.features.numerolineausuario)
      .map { case (line, ps) => line -> Path.sortLinePaths(ps) }

    val WeightStationStation = 2000
    val WeightStationPlatform = 10
    val metroGraph: Graph[MetroNode, WDiEdge] =
      new Metro(sortedLinePaths, WeightStationStation, WeightStationPlatform).buildMetroGraph()

    // OD matrix and district data (generated by scripts/build_od_matrix.py)
    val odMatrix: ODMatrix = ODParser.parseODMatrix(
      scala.io.Source.fromFile("data/madrid/od_matrix.json").mkString)
    val districtData: DistrictData = ODParser.parseDistrictData(
      scala.io.Source.fromFile("data/madrid/district_to_stations.json").mkString)
    scribe.info(s"OD matrix loaded (source=${odMatrix.source}, ${odMatrix.od.size} hours)")
    scribe.info(s"District data loaded (${districtData.districtToStations.size} districts, ${districtData.empresaToDistrict.size} stations)")

    // Launch typed ActorSystem with a Guardian behavior
    val system: ActorSystem[Guardian.Command] = ActorSystem(
      Guardian(metroConf, metroGraph, sortedLinePaths, paths, stationIdsEntrance, odMatrix, districtData),
      "metro-system"
    )

    // Start WebSocket HTTP server using classic adapter
    implicit val classicSystem: org.apache.pekko.actor.ActorSystem = system.toClassic
    import classicSystem.dispatcher
    def broadcastPaused(): Unit = {
      val p = SimClock.isPaused
      WebSocket.sendStat("simPaused", s"""{"message": "simPaused", "paused": $p}""")
    }

    // Register command handler for messages from the browser
    WebSocket.setCommandHandler { text =>
      Try(Json.parse(text)).toOption.foreach { json =>
        (json \ "message").asOpt[String] match {
          case Some("reset") =>
            SimClock.reset()
            WebSocket.resetSnapshot()
            WebSocket.sendStat("simPaused", """{"message": "simPaused", "paused": true}""")
            CommandBus.fireReset()
          case Some("setSpeed") =>
            val factor = (json \ "factor").asOpt[Double].getOrElse(SimClock.speedFactor)
            SimClock.setSpeed(factor)
            val tm = 1.0 / SimClock.speedFactor
            WebSocket.sendStat("timeMultiplier", s"""{"message": "timeMultiplier", "multiplier": $tm}""")
          case Some("pause") =>
            SimClock.pause()
            broadcastPaused()
          case Some("resume") =>
            SimClock.resume()
            broadcastPaused()
          case Some("requestTrainPersons") =>
            (json \ "trainId").asOpt[String].filter(_.nonEmpty).foreach(CommandBus.fireRequestTrainPersons)
          case Some("requestPlatformPersons") =>
            (json \ "platformId").asOpt[String].filter(_.nonEmpty).foreach(CommandBus.fireRequestPlatformPersons)
          case Some("trackPerson") =>
            (json \ "personId").asOpt[String].filter(_.nonEmpty).foreach(CommandBus.fireTrackPerson)
          case Some("untrackPerson") =>
            CommandBus.fireUntrackPerson()
          case Some("queryPath") =>
            for {
              from <- (json \ "from").asOpt[String].filter(_.nonEmpty)
              to   <- (json \ "to").asOpt[String].filter(_.nonEmpty)
            } WebSocket.sendStat("pathResult", PathDebugger.findPath(metroGraph, from, to))
          case _ => ()
        }
      }
    }

    val route: Route = path("ws") { handleWebSocketMessages(WebSocket.listen()) }
    Http().newServerAt("0.0.0.0", 8081).bind(route).onComplete {
      case Success(binding) =>
        println(s"Listening at ${binding.localAddress.getHostString}:${binding.localAddress.getPort}")
        Thread.sleep(4000)
        val tm = 1.0 / SimClock.speedFactor
        WebSocket.sendStat("timeMultiplier", s"""{"message": "timeMultiplier", "multiplier": $tm}""")
      case Failure(ex) => throw ex
    }
  }
}


object Guardian {

  sealed trait Command
  case class AdjustTrainsForHour(hour: Int) extends Command

  // Fraction of max trains per line per hour (Madrid Metro schedule approximation)
  private val TrainFractionByHour: Map[Int, Double] = Map(
    6 -> 0.35, 7 -> 0.55, 8 -> 0.90, 9 -> 0.90, 10 -> 0.70,
    11 -> 0.60, 12 -> 0.60, 13 -> 0.65, 14 -> 0.70, 15 -> 0.65,
    16 -> 0.60, 17 -> 0.80, 18 -> 0.90, 19 -> 0.90, 20 -> 0.75,
    21 -> 0.60, 22 -> 0.45, 23 -> 0.30
  )

  def apply(
    metroConf: MetroConf,
    metroGraph: Graph[MetroNode, WDiEdge],
    sortedLinePaths: Map[String, Seq[Path]],
    allPaths: Seq[Path],
    stationIdsEntrance: Map[StationIds, Option[Entrance]],
    odMatrix: ODMatrix,
    districtData: DistrictData,
  ): Behavior[Command] =
    Behaviors.setup[Command] { context =>

      // UI actor
      val ui = context.spawn(UI(), "ui")

      // Line actors
      val lineActors: Map[String, ActorRef[LineMessage]] = sortedLinePaths.keys.map { l =>
        l -> context.spawn(Line(ui, "L" + l), "L" + l)
      }.toMap

      // Station actors (one per unique station name in graph)
      val stationActors: Map[String, ActorRef[StationMessage]] = metroGraph
        .nodes
        .filter(x => x.value.name.startsWith(Metro.StationPrefix))
        .map { x =>
          val lineId = x.value.lines.headOption.getOrElse("")
          val lineActor = lineActors.getOrElse(lineId.stripPrefix("L"), lineActors.values.head)
          x.value.name -> context.spawn(Station(lineActor, x.value.name), x.value.name)
        }
        .toMap

      // Platform actors per line
      val platformActors: Map[String, Map[String, ActorRef[PlatformMessage]]] =
        (for {
          (lineKey, lineActor) <- lineActors
        } yield {
          val linePlatforms: Map[String, ActorRef[PlatformMessage]] = metroGraph
            .nodes
            .filter(x => x.value.lines.contains("L" + lineKey))
            .filter(x => x.value.name.startsWith(Metro.PlatformPrefix))
            .map { x =>
              x.value.name -> context.spawn(Platform(lineActor, ui, x.value.name), x.value.name)
            }
            .toMap
          lineKey -> linePlatforms
        }).toMap

      val allPlatformActors: Map[String, ActorRef[PlatformMessage]] =
        platformActors.values.reduce(_ ++ _)

      // Wire platform → next platform
      metroGraph
        .nodes
        .filter(x => x.value.name.startsWith(Metro.PlatformPrefix))
        .foreach { x =>
          val current = allPlatformActors(x.value.name)
          x.diSuccessors
            .filter(s => s.value.name.startsWith(Metro.PlatformPrefix))
            .foreach { z =>
              val next = allPlatformActors(z.value.name)
              current ! SetNextPlatform(next)
            }
        }

      val random = new Random

      val pathByName: Map[String, parser.Path] = allPaths.map { pp =>
        Metro.platformName(pp.features.denominacion, pp.features.codigoanden) -> pp
      }.toMap

      // Spawn a train at a specific platform
      def spawnTrainAt(start: ActorRef[PlatformMessage]): ActorRef[TrainMessage] = {
        val uuid  = java.util.UUID.randomUUID.toString
        val train = context.spawn(Train(ui, pathByName), uuid)
        train ! Move(start)
        train
      }

      // Spawn a train at a random platform (used for dynamic additions mid-service)
      def spawnTrainRandom(platforms: Seq[ActorRef[PlatformMessage]]): ActorRef[TrainMessage] =
        spawnTrainAt(platforms(random.nextInt(platforms.size)))

      // Sorted platforms for a line (matches the physical track order)
      def sortedPlatformsForLine(lineKey: String, linePlatforms: Map[String, ActorRef[PlatformMessage]]): Seq[ActorRef[PlatformMessage]] = {
        val sorted = sortedLinePaths
          .getOrElse(lineKey, Seq.empty)
          .flatMap { p =>
            val name = Metro.platformName(p.features.denominacion, p.features.codigoanden)
            linePlatforms.get(name)
          }
        if (sorted.nonEmpty) sorted else linePlatforms.values.toSeq
      }

      // Mutable train tracking per line
      val trainsByLine = scala.collection.mutable.Map[String, scala.collection.mutable.Buffer[ActorRef[TrainMessage]]]()

      // Initialize trains for 6 am — evenly spaced along the sorted platform sequence
      platformActors.foreach { case (lineKey, linePlatforms) =>
        val platforms = sortedPlatformsForLine(lineKey, linePlatforms)
        val maxTrains = math.max(1, platforms.size / 2)
        val initialCount = math.max(1, math.round(TrainFractionByHour(6) * maxTrains).toInt)
        val step   = platforms.size.toDouble / initialCount
        val offset = random.nextInt(platforms.size)
        val buf = scala.collection.mutable.Buffer[ActorRef[TrainMessage]]()
        for (i <- 0 until initialCount) {
          val idx = (offset + (i * step).toInt) % platforms.size
          buf += spawnTrainAt(platforms(idx))
        }
        trainsByLine(lineKey) = buf
        scribe.info(s"Line $lineKey: $initialCount trains at 06:00 (max $maxTrains, step=${step.toInt})")
      }

      // Schedule hourly train count adjustments
      def scheduleHourlyAdjustments(): Unit = {
        for (h <- 7 to 23) {
          val targetSimMs = h.toLong * 3600L * 1000L
          SimClock.scheduleAt(targetSimMs) { () => context.self ! AdjustTrainsForHour(h) }
        }
      }
      scheduleHourlyAdjustments()

      // Simulator
      val actorsByName: Map[String, ActorRef[_]] =
        stationActors ++ allPlatformActors

      val simulatorRef = context.spawn(
        Simulator(ui, actorsByName, metroGraph, stationIdsEntrance, odMatrix, districtData),
        "simulator"
      )

      val allPlatformSeq = allPlatformActors.values.toSeq

      CommandBus.onReset { () =>
        stationActors.values.foreach(_ ! ResetStation)
        allPlatformActors.values.foreach(_ ! ResetPlatform)
        trainsByLine.values.flatten.foreach { train =>
          val p = allPlatformSeq(random.nextInt(allPlatformSeq.size))
          train ! ResetTrain(p)
        }
        simulatorRef ! ResetSimulator
        scheduleHourlyAdjustments()
      }
      CommandBus.onRequestTrainPersons    { trainId  => TrainRegistry.send(trainId, RequestPersonList) }
      CommandBus.onRequestPlatformPersons { anderId  => PlatformRegistry.sendByAnden(anderId, RequestPlatformPersonList) }
      CommandBus.onTrackPerson   { personId => simulatorRef ! TrackPerson(personId) }
      CommandBus.onUntrackPerson { ()        => simulatorRef ! UntrackPerson }

      Behaviors.receiveMessage[Command] {
        case AdjustTrainsForHour(h) =>
          val fraction = TrainFractionByHour.getOrElse(h, 0.30)
          platformActors.foreach { case (lineKey, linePlatforms) =>
            val platforms = linePlatforms.values.toSeq
            val maxTrains = math.max(1, platforms.size / 2)
            val target  = math.max(1, math.round(fraction * maxTrains).toInt)
            val buf     = trainsByLine(lineKey)
            val current = buf.size
            if (target > current) {
              val adding = target - current
              for (_ <- 1 to adding) buf += spawnTrainRandom(platforms)
              scribe.info(s"Hour $h: +$adding trains on line $lineKey → ${buf.size}/${maxTrains}")
            } else if (target < current) {
              val retiring = current - target
              buf.take(retiring).toSeq.foreach { t =>
                t ! RetireTrain
                buf -= t
              }
              scribe.info(s"Hour $h: -$retiring trains on line $lineKey → ${buf.size}/${maxTrains}")
            }
          }
          Behaviors.same
      }
    }
}
